### ISSUE TITLE
Remove expression etc if no data

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#11]
remove superfluous " expressing  that is part of an "

e.g.

Db1
		
ID: VFB_00030769

Definition:
A antennal mechanosensory and motor center AMMC Db1 neuron expressing that is part of an

Type:
antennal mechanosensory and motor center AMMC Db1 neuron

**Comment by dosumis** [comment]
Fixed.  Refactored def roller should avoid this kind of issue in future.

**Comment by dosumis** [comment]
This issue was moved to VirtualFlyBrain/VFB_owl#30
