### ISSUE TITLE
extend tap processing to support splits

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#113]
TAP statements have a comment associated with them via feature_expressionprop:

fb_2018_06_08*=> select value from feature_expressionprop where feature_expression_id in ('277213', '277214') and type_id = '101625';

=>

when combined with @FBtp0099560:PBac{R73H08-p65.AD}@ (combination referred to as 'MB090C') 
when combined with @FBtp0099534:P{R25D01-p65.AD}@ (combination referred to as 'MB077B')

\* Not released at time of writing

Outline spec for code:

(a) identify when TAP statements have these attached 
(b) Parse out the ID of the partner line
(c) MERGE a node for the split expression pattern 
(d) attach annotation to this node.

Potential gotchas:

* TAP is not synonymous with expression table in this case - comment is attached to feature_expression -not feature.
* Need to save ID of partner line until graph navigation has reached the first construct in the split
* Redundancy?  Is TAP only attached to DBD with AD always in comment? (CC @ah963)

**Comment by dosumis** [comment]
Extension of initial query in expression_runner.py is simple. This works

```sql
SELECT pub.uniquename as fbrf,
  f.uniquename as fbid, e.uniquename as fbex,
  fep.value as comment
  FROM feature_expression fe
  JOIN pub ON fe.pub_id = pub.pub_id
  JOIN feature f ON fe.feature_id = f.feature_id
  JOIN expression e ON fe.expression_id = e.expression_id
  LEFT OUTER JOIN feature_expressionprop fep 
       ON fe.feature_expression_id = fep.feature_expression_id
  WHERE (fep.type_id = '101625' OR fep.type_id is NULL)
```

Note - using left outer join + disjunctive WHERE clause is needed to return TAPs with no comments

**Comment by dosumis** [comment]
Integrating addition of split expression patterns will be tricky though, as expression patterns are currently added in batch from expressed transgenes without reference to the datastructure that keeps feature associated with TAP etc.

**Comment by ah963** [comment]
> Redundancy? Is TAP only attached to DBD with AD always in comment? 

TAP is attached to both DBD and AD with a reciprocal comment in the <note> field

**Comment by dosumis** [comment]
> TAP is attached to both DBD and AD with a reciprocal comment in the note field

Good to know.  Hopefully not be a problem for scripting except for slowing things down by trying to add split TAPs twice.

**Comment by ah963** [comment]
Can you restrict the scripting to only looking Scer\GAL4 (or LexA), ie only the DBD rather than Hsap\RELA which would be the AD?

**Comment by dosumis** [comment]
FIxed
