### ISSUE TITLE
pub nodes in pdb without Entity label

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#128]
```MATCH (n:pub) where n:Entity RETURN count(n)``` 1117
```MATCH (n:pub) where not n:Entity RETURN count(n)``` 2059

**Comment by Robbie1977** [comment]
More importantly, missing Individual label

**Comment by Robbie1977** [comment]
Seems to relate to publications loaded not via KB so are (assuming) OWL loaded pubs labelled with Individual?

**Comment by Robbie1977** [comment]
@dosumis Quick fix applied to get this moving (https://github.com/VirtualFlyBrain/VFB_neo4j/commit/75281c56d67d2c33cda4d5ed7bdc5924ecb7ad08) but probably needs to be investigated further as should be handled previously and presumably was so not sure what broke when?

**Comment by dosumis** [comment]
Note tp self:
`MERGE` here: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/flybase2neo/pub_tools.py#L36
 should be `pub:Individual`
