### ISSUE TITLE
Gross category labels missing in bocian neo4j

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#13]
Match (n {short_form:'VFB_00016207'}) RETURN n, labels(n)
[Individual, VFB, _Individual]

Missing 'Neuron'

**Comment by Robbie1977** [comment]
Also applies to Class:
FBbt_00005106
[Class, VFB, _Class]

**Comment by dosumis** [comment]
Should be built and tested on Eccles first.  The copied across to Bocian.  AFAIK, the scripts that side-load data following the OLS build still need to be run by hand on Eccles.  It would be great if you could package them up into a Jenkins job.

**Comment by Robbie1977** [comment]
There also missing on eccles. 

When I have time I'm going to move the loading direct bocian (dev version) then copied to karenin (live version). Are the scripts transitioned to load from the NEO rather than SQL data?

**Comment by dosumis** [comment]
I can see them fine on Eccles:

![image](https://cloud.githubusercontent.com/assets/112839/18884760/b02aabea-84e0-11e6-92ca-2aed1f78cec6.png)

> Are the scripts transitioned to load from the NEO (blanik) rather than SQL (LMB) data?

Not yet.  I've written some of the code.  Not finished yet.

Presumably by moving the dev version to bocian we'll be able to have the complete build run through Jenkins.

**Comment by dosumis** [comment]
Bocian: 
![image](https://cloud.githubusercontent.com/assets/112839/18884852/275ba23c-84e1-11e6-9e35-d7c13ea2aa52.png)

**Comment by dosumis** [comment]
Neither has labels on Individuals, but the latest code should add these: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L59

Probably just needs a fresh build.

**Comment by dosumis** [comment]
Although, looking at the code - the label won't get added to the parent class for each classification (e.g. neuron).   Minor issue.  v.easy to fix.

**Comment by Robbie1977** [comment]
No rush will just need them there to ensure correct query options are displayed.

**Comment by dosumis** [comment]
Rebuild should fix.

(Query option for :Neuron:Individual = NBlast?)

**Comment by Robbie1977** [comment]
At the moment that is all we have was more concerned with the class queries.

**Comment by dosumis** [comment]
In the current build, all the labels for classes are present apart from on the parent classes (e.g. neuron doesn't have a label but all subclasses of neuron do).

**Comment by Robbie1977** [comment]
@dosumis This is still an issue on bocian loaded using jenkins as the geppetto testing requires the 'synaptic neuropil' classification.

**Comment by Robbie1977** [comment]
![image](https://cloud.githubusercontent.com/assets/4630768/21613488/5670de32-d1cd-11e6-8d36-1fd08f742912.png)

**Comment by dosumis** [comment]
The script that adds these is missing from the Jenkins job: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py  (was previously running on Eccles).

**Comment by dosumis** [comment]
Fixing now.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21616613/029d5990-d1da-11e6-9df0-d91da23da548.png)

**Comment by dosumis** [comment]
Note - labels now on individuals too (as discussed above), so determining menus will require 2 labels:  Class/Individual:Neuron/Synaptic_neuropil/etc

**Comment by Robbie1977** [comment]
great thanks
