### ISSUE TITLE
pattern.add_anatomy_image_set issue adding image with special characters in name

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#142]
Having real issues finding a syntax that works for all 3 of the Felsenberg2018 set. Tried several escapes and variants on tick/apostrophe any suggestions?

FYI I just get 'FAILED' on runs where the syntax is good enough not to break the cmd's string itself.

https://github.com/VirtualFlyBrain/StackLoader/blob/master/history/FAFB201909.py#L261

**Comment by dosumis** [comment]
Use double quotes in your python and don't escape?

**Comment by dosumis** [comment]
Is this still an issue or was it just fixed by different  quoting?
