### ISSUE TITLE
Add loading check for existing DBxrefs when new images are added.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#148]
This will work for SKIDS and FlyCircuit IDs/names.  

It is problematic for FlyLight - as the IDs are not for images but for lines (driver or split lines) for which multiple images are available.  Given that, we can't write a generic, hard-fail test without some additional info in the KB.  Maybe add something to Site node to record whether links are 1:1 or many:1 ?

@Robbie1977 - for an actual image check, should we be storing a checksum?  Is this practical? This would allow checks for FlyLight too.

**Comment by Robbie1977** [comment]
Re Checksum: Potentially although we then need to decide which point to check and if we change header this would affect it. Maybe simply a voxel count might be more useful and informative. Can be added at the same time as the image checks after processing.

**Comment by dosumis** [comment]
Have made duplicate dbxrefs illegal for now.  But should probably make this optional.  Checksums or equivalent are a separate issue.
