### ISSUE TITLE
Ito Half Brain template issues

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#15]
VFBi_00030786 doesn't exist only VFBc_00030786 exists.

This is in contrast to how JFRC2 is setup

**Comment by Robbie1977** [comment]
@dosumis this is probably the next priority as is blocking template switching testing.

**Comment by dosumis** [comment]
Seem to remember another ticket or perhaps a slack thread with full details of VFBi/c ID issues.  Do you remember where this might be?

**Comment by Robbie1977** [comment]
Slack Oct 12th

**Comment by Robbie1977** [comment]
But that issue was resolved the Half Brain appears to be something different as is allocated as a 'Thing'

**Comment by dosumis** [comment]
As far as I can tell this has been superseded by schema changes.  Closing.
