### ISSUE TITLE
Template label has vanished

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#16]
@dosumis Which script should add this?

**Comment by dosumis** [comment]
https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L61

**Comment by dosumis** [comment]
Note - the channel is the template, not the anatomical structure.

**Comment by Robbie1977** [comment]
https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L61

MATCH (image:Individual)-[:Related { label: 'has_background_channel'}]->(channel:Individual)

Returns both VFB_00017894 & VFBc_00017894 as well as brainname

**Comment by dosumis** [comment]
Absence of label is down to ordering of scripts in Jenkins job.  Need to push this script to end (after loading of channel and image inds).

**Comment by Robbie1977** [comment]
moving now

**Comment by Robbie1977** [comment]
The Template label is now fixed with one issue concerning the channel placement:

The SIP shows it's template as the channel JFRC but most other neuropil domains show (as they previously did) the template instance JFRC direct. This is causing issues as needs to be consistent - ideally with a user readable label.

```MATCH (i:Individual { short_form: 'VFB_00030628' } )<-[:Related{label:'depicts'}]-(c:Individual)<-[:Related{label:'has_signal_channel'}]-(im:Individual)-[:Related{label:'has_background_channel'}]->(t:Template) RETURN substring(im.short_form,0,3)+'/'+substring(im.short_form,3,1)+'/'+substring(im.short_form,5,4)+'/'+substring(im.short_form,9,4)+'/' as imageDir, t.short_form as tempId, t.label as tempName  ```

```imageDir	tempId	tempName
VFB/i/0003/0628/	VFBc_00017894	JFRC2_template_c```

where as ME gives:
```imageDir	tempId	tempName
VFB/i/0003/0624/	VFB_00017894	JFRC2_template```
