### ISSUE TITLE
Implement add new type in VFB_neo4j

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#175]
- label, synonyms, exemplar - see:

https://github.com/VirtualFlyBrain/vfb-data-ingest-api/blob/3b5b8ab723e061218f12c6c65f03b48796e49f66/vfb_curation_api/database/models.py#L107

**Comment by dosumis** [comment]
Spec: 
  - Extend pattern_writer with new method
  - Add new type to KB with ID = UUID
  - Add INSTANCEOF & exemplar_of links to some specified individual (perhaps we should allow multiple individuals here?  It is often hard for users to choose  one exemplar)
  - Add parent class

**Comment by dosumis** [comment]
@Robbie1977; @Clare72   - This ticket  = plan for adding new neuron classes to KB.   

Provisional plan  - a temp ID (UUID) which is persistent and resolvable.  This should resolve to an FBbt later - if it gets added -  i.e. we would  need  a redirect mechanism.

Alternative proposal:  Reserve an ID space in FBbt.  Generate  with FBbt  IDs in DB and add a Robot  pipeline for turning these into FBbt classes.

Thoughts?

**Comment by Robbie1977** [comment]
It would be better to use an FBbt Id from the beginning if possible (not sure how they are allocated anymore). Ideally, the KB could be allocated a range to use which would then be used when creating in FBbt.

**Comment by dosumis** [comment]
1. Reserve an FBbt ID range in the usual way. @Clare72  - at least 20,000 IDs - paste details into this ticket.
2. New terms should have a flag that  is recognised by FBbt update to prevent it throwing  an  error report when it  encounters an ID not in FBbt @dosumis 
3. The flag can also be used to drive a script that generates a robot template which can be folded into FBbt build & release.  @Clare72 
   * Query: MATCH (c:Class) WHERE c.short_form =~ 'FBbt_.+'  AND  <some clause to  check  for flag>  return  properties(c) limit 5
   * Minimal robot template:  ID, label,  http://purl.org/dc/elements/1.1/creator, description


TBD: when and how to trigger a  robot build to import terms into FBbt.

Advantage of early release:  PURLS resolve.  Disadvantage: New, used defined terms with very  minimal def etc may cause  confusion among FBbt users (e.g. scAtlas).

**Comment by Clare72** [comment]
FBbt:20000000 - FBbt:20049999

>EM_data:FBbt	20000000-20049999   namespace-id-rule: * FBbt:$sequence(8,20000000,20049999)$

**Comment by dosumis** [comment]
That's a very old ID range spec file (designed to be read by OBO-Edit).   We should probably move to this https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/src/ontology/fbbt-idranges.owl to match how other OBO-ish ontologies do this.

**Comment by Clare72** [comment]
Yeah, noticed that we got the fbbt-idranges.owl with the ODK migration and it has been in the back of my mind for a while to get round to switching this over (for other ontologies too).
There seem to be some VFB IDs in the old [ID_space_log](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/src/ontology/ID_space_log) file - 'FlyCircuit' and 'clones'. I guess these are saved somewhere else and don't need to be kept on the FBbt repo(?)

**Comment by dosumis** [comment]
> There seem to be some VFB IDs in the old ID_space_log file - 'FlyCircuit' and 'clones'. I guess these are saved somewhere else and don't need to be kept on the FBbt repo(?)

Yes. Ancient history - no longer relevant.  This is from before we had a DataBase to manage VFB IDs.
