### ISSUE TITLE
GNG (FBbt_00014013) has no synaptic neuropil labels

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#18]
Can't query neurons if it's not synaptic neuropil or some synaptic derivative? Has no labels beyond Class (& VFB)

Probably not the only example but the first I've come across since latest build.

**Comment by dosumis** [comment]
Easy to fix.  I'll add the Neuropil label to subclasses of ganglion.

**Comment by dosumis** [comment]
Should now get Ganglion label:

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/add_constraints_and_redundant_labels.py#L61

This is consistent with what we've done so far - keeping the gross types indicated by labels in line with ontology classification.   I prefer this to fudging and classifying as 'synaptic neuropil'. We'll need XMI to specify what to do with Ganglia.  I think it makes sense to have the same queries as synaptic neuropil, at least for now.
