### ISSUE TITLE
FlyCircuit Ref

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#19]
in the neo4j Knowledge Base http://flybase.org/reports/FBrf0210580.html is listed as the dataset ref but we ref PubMed ref PMID:21129968 in our existing term info.

Which is correct for the dataset?

**Comment by mmc46** [comment]
FBrf is wrong. Should be

FBrf0212704 == Chiang et al., 2011, Curr. Biol. 21(1): 1–11

PMID is correct.

**Comment by Robbie1977** [comment]
@dosumis I'm happy to change in KB if you want me to but might be prudent to check the others before we use for loading into production.

**Comment by dosumis** [comment]
We should only have one way to say this in the KB.  Seems there are currently two:

http://blanik.inf.ed.ac.uk:7474/browser/

![image](https://cloud.githubusercontent.com/assets/112839/22559973/c6d1e31a-e96a-11e6-80d8-5a39c1a78d2c.png)

![image](https://cloud.githubusercontent.com/assets/112839/22560040/fdae342e-e96a-11e6-9f00-12ef235dc63f.png)

![image](https://cloud.githubusercontent.com/assets/112839/22560096/287ed000-e96b-11e6-8023-1149af8efa61.png)

**Comment by Robbie1977** [comment]
agreed

**Comment by dosumis** [comment]
Dataset link not always a ref:

e.g. Dickson_VT  has  ds.dataset_link = http://stockcenter.vdrc.at/control/vtlibrary/ 

Need spec for various types of link datasets (and the images that belong to them) can have.

(BTW - happy for you to fix or delete existing).

**Comment by Robbie1977** [comment]
Fixed:
```MATCH (d:data_source {name:'Chiang2010'}) SET d.dataset_link='http://flybase.org/reports/FBrf0212704.html'```
Also corrected (as the website was changed in Dec):
```
MATCH (d:data_source {name:'Dickson_VT'}) SET d.dataset_link='http://stockcenter.vdrc.at/control/keywordsearch?VIEW_SIZE=100&SEARCH_CATEGORY_ID=VDRC_All&library=VT-GAL4';
```
