### ISSUE TITLE
Import expression data from VFB

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#2]
Data in FlyBase:
### linking features, expression and pubs.

feature_expression table links features to expression statements and pubs.

The features linked here are transcripts/proteins. For WT gene products, it is one hop from here to genes using the feature_relationship table. 2 hops (GP->allele->TG) are required to get to transgenes (insertions).  This mess is currently hidden by VFB view tables.

e.g. 

``` .sql

CREATE TABLE vfbview_transgene_expressed_gp AS
SELECT DISTINCT obj2.feature_id as transgene_feature_id, obj2.name as transgene_name, 
obj2.uniquename as transgene_uniquename, stype.name as gp_type_name, 
fe.feature_id as gp_feature_id
    FROM feature_expression fe
    JOIN feature subj ON (fe.feature_id=subj.feature_id)
    JOIN cvterm stype ON (subj.type_id=stype.cvterm_id)
    JOIN feature_relationship fr1 ON (fe.feature_id = fr1.subject_id)
    JOIN cvterm rel1 ON (fr1.type_id = rel1.cvterm_id)
    JOIN feature_relationship fr2 ON (fr1.object_id = fr2.subject_id)
    JOIN cvterm rel2 ON (fr2.type_id = rel2.cvterm_id)
    JOIN feature obj2 ON (fr2.object_id = obj2.feature_id)
    JOIN feature_relationship fr3 ON (fr1.object_id = fr3.subject_id)
    JOIN cvterm rel3 ON (fr3.type_id = rel3.cvterm_id)
    WHERE rel1.name='associated_with'
    AND rel2.name='associated_with'
    AND rel3.name='alleleof'
    AND obj2.uniquename ~ 'FBtp|FBti';

```

It probably makes sense to keep these links collapsed down for VFB neo4J representation.

This view table query can be used to generate a set of transgene nodes sufficient to represent transgene expression data.
### Expression statements

[This script](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/master/tools/perl_modules/trunk/TAPget.pm) provides a useful reference for the shape (and complexity!) of expression statements in FlyBase.

Components:

anatomy: primary anatomical term
anatomy_of: translate to 'anatomy that part_of some %s'
anatomy qualifier: qualifies primary anatomy term (ignore?)
assay: assay used to assess expression
cc: cellular component localized to
start_stage: stage expression starts at
end_stage: stage expression ends at.
amp_stages  - multiple named stages during which expression occurs
stage qualifier  - Ignore
cellular component qualifier  - Ignore?

Not sure we need all of these.  A minimal implementation takes anatomy & maybe stage.

Strategy:
- We make an expression pattern class node - instances -> images
- Expression pattern has an overlaps relationships to nodes corresponding to expression statements, but typed as anatomy/CC and linked to CC/anatomy terms as appropriate.
- expression statement node also links to node for stage range, that in turn links to start and end stages (but AMP stages?
- expression statement also links to reference node ? (Or as attribute on edge?)

Draft schema

``` .cql
(ep:expression pattern { label :  "expression pattern of X", short_form  : "VFB…." }) 

(ep)-[:instanceOf]->(:Individual:Anatomy: { short_form : "VFB_1234567" })

(ep)-[expresses]->(:genetic_feature {  label : 'p{X}', short_form : "FBbi..." })

(ep)-[:overlaps { short_form : 'RO_…',  pubs: ["FBrf12343567"]}]
->(as:Class:Anatomy { "label" :  'lateral horn  - from S-x to S-y', short_form : 'FBex...', assay: ''})

(as)-[SubClassOf]->(:Anatomy { label:  'lateral horn', short_form: "FBbt_...." })

(as)-[during]->(sr:stage { label: 'stage x to y'} )

(sr)-[start]->(:stage { label: 'stage x', short_form: 'FBdv_12345678' }

(sr)-[end]->(:stage { label: 'stage y', short_form: 'FBdv_22345678' }
```

Relationship to pub node:

In terms of the semantics, it makes most sense for the pub to be specified on the overlaps edge (which it supports).  The alternative would be to have intermediate nodes between **ep** and **as**, each unique for each ref and linking to the relevant ref node.  Feels hacky and doesn't fit nicely with conversion to OWL.  Probably better use a second round lookup for pub info, or to have parallel lists with IDs and minirefs on the occurs in edge.

Implementation:

Python call to open SQL DB + either Python requests or py2neo

Addition of content from FB can be split into 3 rounds, relying on specification of unique identifiers + merge on create:

Round 1: Add all classes transgenes for which we have expression data
Round 2: Add all expression statements (relying on FBex as unique identifier)
Round 3: Link transgenes to expression statement nodes via expression pattern nodes & occurs in edges, adding pubs.
Round 4: Link images

**Comment by dosumis** [comment]
Making stage queryable: It should be possible to use OWL reasoning to find lead nodes in the ID range specified.  This would allow all stages of expression to be directly linked to as.  Queries by stage (either directly or via the partonomy in FBdv) would then be straightforward.

**Comment by dosumis** [comment]
New [GraphGist]( http://portal.graphgist.org/graph_gists/1cead583-7fdf-4f4d-95c8-07b828168b8c) documents schema

**Comment by dosumis** [comment]
How to link images:

1. First need to ensure no duplicate nodes for FB features in import.  For this use merge statements, matching on short_form ids.

2. Use cypher query to find Instances of expression pattern + expresses :   

~~~~~~~~~~.cql
MATCH (ep:Class { label: 'Expression pattern' })<-[:InstanceOf]-(n:Individual)-[:expresses]->(:Class { short_form: 'FBbi1234567' } )  RETURN  ep
~~~~~~~~~~

**Comment by nstaudt** [comment]
Hi David,

are you going to be in Helen's office for the meeting at 2pm or are you 
not on site?

Thanks,

Nicole

**Comment by Robbie1977** [comment]
@dosumis How is work going on import_expression_data.py as trying to replicate existing queries?

**Comment by dosumis** [comment]
duplicate with #43
