### ISSUE TITLE
Template with domain representation

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#20]
It occurs to me that each domain channel should be linked as one image since they are all one image with multiple numbered channels with the as channel 0 template.

```
(i:Individual {short_form:VFBi_00017894})-[Related {label:has_signal_channel, index:0}]->(c:Individual {short_form:VFBc_00017894})
...
(i:Individual {short_form:VFBi_00017894})-[Related {label:has_signal_channel, index:25}]->(c25:Individual {label:'ME - painted domain JFRC2',short_form:VFBc_00030624});
etc.
```
This would incorporate the actual structure better and encode the index numbers in the edge relationships.

**Comment by Robbie1977** [comment]
@dosumis FYI SIP VFB_00030628 needs checking in the LMB DB as has 2 VFBi's and no VFBc in KB; Recall flagging but just wanted to make a note. No urgency!

**Comment by Robbie1977** [comment]
Fixed SIP in KB:
```MATCH (i:Individual {short_form:'VFBi_00030628'}) SET i.iri='iri: http://www.virtualflybrain.org/owl/VFBc_00030628',i.short_form='VFBc_00030628';
MATCH (i:Individual {short_form:'VFBi_00020204'}) SET i.iri='iri: http://www.virtualflybrain.org/owl/VFBi_00030628',i.short_form='VFBi_00030628';
```

**Comment by Robbie1977** [comment]
@dosumis FYI VFB_00030838 MB_CA is an unused duplicate of MB_CA VFB_00030821 (id currently used). The ID is not listed as anything else.

**Comment by Robbie1977** [comment]
FYI VFB_00030830 missing entirely (VFB,VFBi,VFBc) but it's anatomy term FBbt_00110653 is in the KB

**Comment by dosumis** [comment]
@Robbie1977  - is this still relevant or can we close?

**Comment by dosumis** [comment]
@Robbie1977  - on second thoughts - closing anyway.  If any relevant content here, please resurrect.
