### ISSUE TITLE
Change kb writer to adjust to changes in rdfs_label representation

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#202]
kbw no longer has a label property with value string.  Instead it has rdfs_label: [string1]

If we keep this then all VFB_neo4j methods that write labels  (in KB_tools,  feature_tools & expression_tools) need to be revised. 

TBD: Are we sure this change  to KB is necessary?

In favour:  
- It is critical to keep redundancy in KB to a minimum.  We should not have rdfs_label + label   (but we could just have label)
- When loading reference classes and properties from sources, we will occasionally have to deal with classes with multiple labels (but could resolve in config?)

Against: 
 - We have no need to support multiple labels on individuals maintained in KB
 - Needless churn.

**Comment by dosumis** [comment]
Closing as we decided to adjust the schema instead of adapting code.

**Comment by dosumis** [comment]
Breakdown of issues

1. We **need** a *single* property for recording term label (name) in KB. 
2. If we don't use rdfs_label for this, then export generate rdfs_label axioms from this.
2. Ideally the value type of this property will be a string, not a list of strings, as changing VFB_neo4j to always use lists will involve lots of churn and messy code.
3. Changing the name of this property from label (as now) to rdfs_label is tolerable, but would also involve churn - chasing down required changes scattered through the VFB_neo4j code base.

**Comment by dosumis** [comment]
CC @matentzn

**Comment by matentzn** [comment]
Closing in favour of https://github.com/VirtualFlyBrain/vfb-pipeline-kb2kb/issues/4
