### ISSUE TITLE
Automatically update obsoleted terms when replaced by is present

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#222]
Relevant code: 

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/KB_tools.py#L512
node_importer.update_from_obograph()

- [ ] Under node_importer add a function that does lookup of replaced_by / consider and rolls cypher to update if replaced_by found + adds to statement stack - otherwise issues warning for curator to check
- [ ] Call this function when obsoletes in use are found while running node_importer.update_from_obograph
- [ ] OPTIONAL Add a test for this using a hacked Ontology file in JSON with some well used term set to OBSOLETE.  Can be tested against containerised KB on Travis.

note - to add cypher statements to stack for loading, use `self.statements.append(<cypher statement>)`

**Comment by Clare72** [comment]
now implemented
