### ISSUE TITLE
Set up GitHub Actions CI testing

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#246]
Travis tests are failing on Master, and haven't been run for 6months!

**Comment by Robbie1977** [comment]
Setup: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/.github/workflows/python-app.yml 
Running: https://github.com/VirtualFlyBrain/VFB_neo4j/runs/4296543049?check_suite_focus=true
