### ISSUE TITLE
Update FeatureMover.gen_split_ep_feat to use FBco

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#284]
Update fm.gen_split_ep_feat to process FBco - this would need a step that finds FBtp/ti. We already have a method for that on FeatureMover [L306](https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/flybase2neo/feature_tools.py#L306).  Or we could write that into the original expression query (?)

- [ ] Add FlyBase linkouts using FBco IDs.
- [ ] Design and implement strategy for adding synonyms and minting symbols.

**Comment by dosumis** [comment]
Notes and relevant SQL queries here https://docs.google.com/document/d/1VnivaeleLBLQj7ttjaqXpKrB4pr5pyIeQn4NkpAuNWo/edit#heading=h.8jr3odkyo7n9

**Comment by Clare72** [comment]
>Update fm.gen_split_ep_feat to process FBco

decision in 15/04/24 meeting to make new method and leave gen_split_ep_feat alone for now

**Comment by dosumis** [comment]
No longer needed as loaded upstream as OWL
