### ISSUE TITLE
Decide on VFB entities to link FBcos to

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_neo4j#288]
[Example FBco page](http://flybase.org/reports/FBco0000056.htm)

FBco entities are linked to alleles and not directly to transposons/insertions (@admclachlan to check this with FlyBase).

Some alleles may be (genuinely) linked to multiple transposons, so it seems that expression curation at FlyBase will no longer be uniquely linked to FBtp/ti (@admclachlan to check this with FlyBase).

VFB links expression to 'VFBexp_' nodes, which combine two FBtp/ti identifiers to represent a split expression pattern.
For images - these are always correctly represented.
For expression - for one hemidriver we take an FBtr ID and map to FBal, then FBtp, so we may be choosing the wrong entity. The other hemidriver FBtp/FBti comes from directly the free text, so this is currently correct. I think we don't know which half, if either is currently wrong.

OPTIONS:
1. Continue to use VFBexp nodes based on FBtp, but these will be chosen arbitrarily where we are starting from FBco. We may also end up with multiple VFBexp nodes representing the same FBco (unavoidable if we have images with different transposons for the same allele combination).
2. Switch to using VFBexp nodes based on FBal. We will lose some information from images, but will not be synthesising potentially incorrect information for expression. This will probably also be easier for users going between FlyBase and VFB if we use the same naming (based on alleles). This will require more work to retrofit existing data.

**Comment by dosumis** [comment]
Option 3 - switch to using FBco IDs.

**Comment by Clare72** [comment]
That would be option 2 here: https://github.com/VirtualFlyBrain/VFB_neo4j/issues/283

**Comment by Clare72** [comment]
Decision on 13/05/2024 call to switch to using FBco directly (so will eventually need to deprecate VFBexp_ objects). We can for now pull all FBco and associated FBal, later consider how to get FBal we need that are not part of a split.
