### ISSUE TITLE
KB tweaks

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#30]
# Tweaks to KB required following move from LMB.

* New schema for registration (Robbie)
```
MATCH (i:Individual)<-[rd:Related {short_form:'depicts'}]-(c:Individual)<-[ri:Related {short_form:'VFBext_0000003'}]-(im:Individual)-[rt:Related {short_form:'VFBext_0000002'}]->(tc:Individual) 
CREATE (c)-[:in_register_with]->(tc) 
DETACH DELETE im
```

* - [ ] Switch JFRC adult brain template to new source (from Jennett2012)

JennetShinomiya (the one used for painting this brain) seems like an OK source, but perhaps best to create a new one.

* - [ ]  Tag relevant channels as confocal:

```cql
    MATCH (it:Class { label: 'confocal microscopy' }) WITH it
    MATCH (ds:data_source)-[r]-(i:Individual)-[:Related { short_form: 'depicts' }]-(channel:Individual)  
    WHERE not (ds.name in ['JenettShinomya_BrainName', 'BrainName_Ito_half_brain', 'CostaJefferis']) 
    MERGE (it)-[:Related {IRI:'http://purl.obolibrary.org/obo/OBI_0000312',short_form:"OBI_0000312",label:"is_specified_output_of"} ]->(channel)
``` 

* - [ ] Remove erroneous classification on some channels as 'multi-channel image'

(Could actually remove all typing with this once images are deleted as part of refactoring)

*  - [ ] Add missing channels

We have only a handfull of these

```cql
    MATCH (n:data_source)-[r]-(x:Individual) WITH x, n 
    OPTIONAL MATCH
    (x)-[r2:Related { short_form : 'depicts'} ]-(y:Individual) 
    WITH x ,y.label as c, n 
    WHERE c is null and n.name <> "CostaJefferis" return n.name, x.short_form, x.label
```

=>

![image](https://cloud.githubusercontent.com/assets/112839/25489923/3a5c05ce-2b63-11e7-9359-85fa24cedd04.png)

(Perhaps best to wait until new IRI scheme in place?)

* - [x]  Pull licenses from Blanik to KB

* - [x] attribute IRI -> iri (this is needed for generic Neo to Neo scripts

```cql
MATCH (n) WHERE exists(n.IRI)
set n.iri = n.IRI
remove n.IRI

MATCH (n)-[r]-(m) WHERE exists(r.IRI)
set r.iri = r.IRI
remove r.IRI
``` 

* - [ ]  Switch to new schema for linkouts https://github.com/VirtualFlyBrain/VFB_neo4j/issues/27

**Comment by Robbie1977** [comment]
https://hub.docker.com/r/rcourt/docker-neo4j-knowledgebase/builds/ now loads up with latest KB

**Comment by Robbie1977** [comment]
Previous crash caused by java heap issue (https://github.com/neo4j/neo4j/issues/6440) memory expanded, will monitor actual usage. 
```
MATCH (i:Individual)<-[rd:Related {short_form:'depicts'}]-(c:Individual)<-[ri:Related {short_form:'VFBext_0000003'}]-(im:Individual)-[rt:Related {short_form:'VFBext_0000002'}]->(tc:Individual) 
CREATE (c)-[:in_register_with]->(tc) 
DETACH DELETE im
```
Applied to KB
```
Deleted 38543 nodes, deleted 99332 relationships, created 38543 relationships, statement completed in 1986 ms.
```

**Comment by dosumis** [comment]
Looks like these are now either irrelevant or fixed.
