### ISSUE TITLE
KB: DataSets should have a release status flag to filter non-public datasets

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/VFB_neo4j#49]
Introduce Annotation property to that end.

**Comment by dosumis** [comment]
CC @Robbie1977 

Will add

is_public: True/False? 

Should probably just invent internal VFB annotation property for this (as even attributes now need an AP mapping)

**Comment by dosumis** [comment]
MATCH (ds:DataSet) WHERE ds.production = True return collect(ds.label)
=>
["Yu2013", "Ito2013", "Cachero2010", "Jenett2012", "Dickson_VT", "JenettShinomya_BrainName", "Kohl2013", "Matsuo2016", "BrainName_Ito_half_brain"]

I'll add a separate boolean for dev release.
