### ISSUE TITLE
Need to create short_form before scripts run after ols load

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#50]
Need a script to run: 
```MATCH (n) WHERE (not has(n.short_form)) and has(n.iri) set n.short_form=split(n.iri, '/')[-1]```
Before all other side load scripts that rely on short_form existing

**Comment by dosumis** [comment]
What nodes are missing short_form?
AFAIK it's only edges that are missing it.

**Comment by dosumis** [comment]
![image](https://user-images.githubusercontent.com/112839/35626088-85e49dc6-068c-11e8-8044-c0071ae9889f.png)

So pub, DataSet, License and Site all lack short_forms (and some pub nodes are Individuals - coming from KB I think. In future all nodes will be an OWL type: either Class, Individual, ObjectProperty, DataProperty).

But all other Individuals have a short_form.   Closing this ticket.  Please re-open if we need short_forms on DataSet etc.
