### ISSUE TITLE
Simplify edge flipping to work entirely within cypher

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#52]
The Python code doesn't really do much except sub '_' for ' ' in labels.  We can do this in Cypher:

```cql
MATCH (n)-[r:Related]->(m) WITH n, r 
MERGE (n)-[r2:replace(r.label,' ','_') {label:type(r),iri:r.iri}]->(m) 
DELETE r
```

One potential issue:  edges don't have short_forms in the default OLS representation we could potential add this during the same step by deriving from iri:

n.short_form=split(n.iri, '/')[-1]
But this is dangerous though, as shortform delimiter may be either # or / with # taking precedence.

**Comment by Robbie1977** [comment]
see: https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/make_named_edges.py

**Comment by dosumis** [comment]
So - do we worry about short_forms on edges or just forget it?  Happy to leave it if no problems for Geppetto.

**Comment by dosumis** [comment]
AFAIK this is fixed - at least to the extent we need in OLS derived PDB.  All will be sunny shiny and new and usable in the glorious new v2 pipeline world.
