### ISSUE TITLE
Need to add a switch to delete old 'Related' edges

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#53]
Need to add parameter/switch to enable control of delete_old=True/False

https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/neo2neo/make_named_edges.py

**Comment by dosumis** [comment]
Happy to keep old edges for now.  Issue will just go away with new schema.
