### ISSUE TITLE
Erroneous Publication node

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_neo4j#71]
```
"nodes": [
              {
                "id": "130174",
                "labels": [
                  "Individual",
                  "pub"
                ],
                "properties": {
                  "None": "PMID:16902576PMID:24568158"
                }
              }
            ]
```
Not quite sure what to do with this one!

Only one just need to figure out how where the typo is and resolve.

**Comment by Robbie1977** [comment]
G-protein coupled receptor signaling pathway [go:0007186] definition maybe

**Comment by dosumis** [comment]
Looks like an error in GO term imported into FBbt.owl.  Could fix locally but, given this is an import from an ontology we don't control, we need to be robust to errors like this.  Is is causing loading problems?  If not, safe to ignore, if it is we need to harden the loading code - perhaps generating warnings for cases like this.

**Comment by Robbie1977** [comment]
No issue our end really just need to flag to GO

**Comment by dosumis** [comment]
Seems to be fixed  in GO: https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0007186
