### ISSUE TITLE
Set backups for neo4J KB

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_neo4j#9]
We need to move towards [VFB neo4J KB](http://blanik.inf.ed.ac.uk:7474/browser/) being the master for channel and image data.  A first step towards this should be setting up regular database backups. Nightly seems reasonable.

**Comment by Robbie1977** [comment]
Backups running nightly and keeping 120days of archives:
https://blanik.inf.ed.ac.uk:8079/view/NEO4j/job/Backup%20Neo4J%20DB/ws/

We can try a destroy and restore whenever you are ready.
